version: '3'

services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PW}
      MYSQL_DATABASE: ${DB}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      # MYSQL_ROOT_PASSWORD: ${DB_ROOT_PW}
      # MYSQL_DATABASE: ${DB_NAME}
      # MYSQL_USER: ${DB_USER}
      # MYSQL_PASSWORD: ${DB_PASS}
      
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    volumes:
      - pma_vol:/home/ubuntu/pma
    restart: always
    ports:
      - '8888:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: test
      PMA_ABSOLUTE_URI: http://localhost/pma/

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '8000:80'
    restart: always
    volumes:
      - wp_vol:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB}
      
  proxy:
    depends_on:
      - phpmyadmin
    image: nginx:1.23
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  db_data: 
  pma_vol: 
  wp_vol:
